name: Deploy to EC2 (PROD)

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  deployments: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production  # Just add this line
    
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/ubuntu/myspotipal-dev
            git pull origin deploy
            source venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart myspotipal-dev.service
            sudo systemctl restart nginx
            sudo systemctl status myspotipal-dev.service
