name: Deploy to EC2

on:
  push:
    branches: [ deploy ]  # or whatever branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ubuntu
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /home/ubuntu  
          git pull origin deploy
          sudo systemctl restart myspotipal.service
          sudo systemctl status myspotipal.service
