name: Deploy to EC2
on:
  push:
    branches: [ deploy ]

permissions:
  deployments: write
  statuses: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Create GitHub Deployment
      uses: chrnorm/deployment-action@v2
      id: deployment
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        environment: production
        initial-status: in_progress
    
    - name: Check Key Format
      run: |
        if [[ "${{ secrets.SSH_KEY }}" == *"BEGIN OPENSSH PRIVATE KEY"* ]]; then
          echo "Key appears to be in correct format"
        else
          echo "Key format might be incorrect"
        fi
    
    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ubuntu
        key: ${{ secrets.SSH_KEY }}
        debug: true
        script: |
          cd /home/ubuntu  
          git pull origin deploy
          sudo systemctl restart myspotipal.service
          sudo systemctl status myspotipal.service
          
    - name: Update Deployment Status
      if: always()
      uses: chrnorm/deployment-status@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        environment-url: http://${{ secrets.HOST }}
        state: ${{ job.status == 'success' && 'success' || 'failure' }}
        deployment-id: ${{ steps.deployment.outputs.deployment_id }}